<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    
  <main>
        <section>
            <h1>Connexion</h1>
            <form action="#" method="POST">
                <label for="email">Email</label>
                <input type="text" id="email" name="email" placeholder="Entrez votre username" required>
                <label for="password">Mot de passe</label>
                <input type="password" id="password" name="password" placeholder="Entrez votre mot de passe" required>

   
      
                <button type="submit">Envoyer</button>
            </form>
        </section>
    </main>


</body>
</html>