<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Page d'accueil</title>
  <link rel="stylesheet" href="src/public/css/style.css" />
</head>
<body>

  <header>
    <h1>Mon Site MVC</h1>
  </header>

  <main>
      
      <h2>Bienvenue sur mon site !</h2>
       <p>Nous sommes ravis de vous accueillir. Explorez notre contenu ou créez un compte pour commencer.</p>
  </main>

  <footer>
    <p>&copy; 2025 Mon Super Site. Tous droits réservés.</p>
  </footer>

</body>
</html>
